// ─────────────────────────────────────────────────────────────────────────────
// objects-db.js — Static astronomical object catalogue for the observer's log.
// Used by log-ui.js for autocomplete in session entry.
// To add objects: append entries to the relevant section below.
// ─────────────────────────────────────────────────────────────────────────────

window.SKY_OBJECTS_DB = [

  // ── SOLAR SYSTEM ──────────────────────────────────────────────────────────
  { id: 'sun',     name: 'Sun',     cat: 'Solar System', type: 'Star' },
  { id: 'moon',    name: 'Moon',    cat: 'Solar System', type: 'Natural satellite' },
  { id: 'mercury', name: 'Mercury', cat: 'Solar System', type: 'Planet' },
  { id: 'venus',   name: 'Venus',   cat: 'Solar System', type: 'Planet' },
  { id: 'mars',    name: 'Mars',    cat: 'Solar System', type: 'Planet' },
  { id: 'jupiter', name: 'Jupiter', cat: 'Solar System', type: 'Planet' },
  { id: 'saturn',  name: 'Saturn',  cat: 'Solar System', type: 'Planet' },
  { id: 'uranus',  name: 'Uranus',  cat: 'Solar System', type: 'Planet' },
  { id: 'neptune', name: 'Neptune', cat: 'Solar System', type: 'Planet' },

  // ── MESSIER CATALOGUE ─────────────────────────────────────────────────────
  { id: 'm1',   name: 'M1 — Crab Nebula',            cat: 'Messier', type: 'Supernova remnant · Taurus' },
  { id: 'm2',   name: 'M2 — Globular Cluster',        cat: 'Messier', type: 'Globular cluster · Aquarius' },
  { id: 'm3',   name: 'M3 — Globular Cluster',        cat: 'Messier', type: 'Globular cluster · Canes Venatici' },
  { id: 'm4',   name: 'M4 — Globular Cluster',        cat: 'Messier', type: 'Globular cluster · Scorpius' },
  { id: 'm5',   name: 'M5 — Globular Cluster',        cat: 'Messier', type: 'Globular cluster · Serpens' },
  { id: 'm6',   name: 'M6 — Butterfly Cluster',       cat: 'Messier', type: 'Open cluster · Scorpius' },
  { id: 'm7',   name: 'M7 — Ptolemy Cluster',         cat: 'Messier', type: 'Open cluster · Scorpius' },
  { id: 'm8',   name: 'M8 — Lagoon Nebula',           cat: 'Messier', type: 'Emission nebula · Sagittarius' },
  { id: 'm9',   name: 'M9 — Globular Cluster',        cat: 'Messier', type: 'Globular cluster · Ophiuchus' },
  { id: 'm10',  name: 'M10 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Ophiuchus' },
  { id: 'm11',  name: 'M11 — Wild Duck Cluster',      cat: 'Messier', type: 'Open cluster · Scutum' },
  { id: 'm12',  name: 'M12 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Ophiuchus' },
  { id: 'm13',  name: 'M13 — Great Hercules Cluster', cat: 'Messier', type: 'Globular cluster · Hercules' },
  { id: 'm14',  name: 'M14 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Ophiuchus' },
  { id: 'm15',  name: 'M15 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Pegasus' },
  { id: 'm16',  name: 'M16 — Eagle Nebula',           cat: 'Messier', type: 'Emission nebula · Serpens' },
  { id: 'm17',  name: 'M17 — Omega Nebula',           cat: 'Messier', type: 'Emission nebula · Sagittarius' },
  { id: 'm18',  name: 'M18 — Open Cluster',           cat: 'Messier', type: 'Open cluster · Sagittarius' },
  { id: 'm19',  name: 'M19 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Ophiuchus' },
  { id: 'm20',  name: 'M20 — Trifid Nebula',          cat: 'Messier', type: 'Emission/reflection nebula · Sagittarius' },
  { id: 'm21',  name: 'M21 — Open Cluster',           cat: 'Messier', type: 'Open cluster · Sagittarius' },
  { id: 'm22',  name: 'M22 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Sagittarius' },
  { id: 'm23',  name: 'M23 — Open Cluster',           cat: 'Messier', type: 'Open cluster · Sagittarius' },
  { id: 'm24',  name: 'M24 — Sagittarius Star Cloud', cat: 'Messier', type: 'Star cloud · Sagittarius' },
  { id: 'm25',  name: 'M25 — Open Cluster',           cat: 'Messier', type: 'Open cluster · Sagittarius' },
  { id: 'm26',  name: 'M26 — Open Cluster',           cat: 'Messier', type: 'Open cluster · Scutum' },
  { id: 'm27',  name: 'M27 — Dumbbell Nebula',        cat: 'Messier', type: 'Planetary nebula · Vulpecula' },
  { id: 'm28',  name: 'M28 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Sagittarius' },
  { id: 'm29',  name: 'M29 — Open Cluster',           cat: 'Messier', type: 'Open cluster · Cygnus' },
  { id: 'm30',  name: 'M30 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Capricornus' },
  { id: 'm31',  name: 'M31 — Andromeda Galaxy',       cat: 'Messier', type: 'Galaxy · Andromeda' },
  { id: 'm32',  name: 'M32 — Andromeda Companion',    cat: 'Messier', type: 'Galaxy · Andromeda' },
  { id: 'm33',  name: 'M33 — Triangulum Galaxy',      cat: 'Messier', type: 'Galaxy · Triangulum' },
  { id: 'm34',  name: 'M34 — Open Cluster',           cat: 'Messier', type: 'Open cluster · Perseus' },
  { id: 'm35',  name: 'M35 — Open Cluster',           cat: 'Messier', type: 'Open cluster · Gemini' },
  { id: 'm36',  name: 'M36 — Open Cluster',           cat: 'Messier', type: 'Open cluster · Auriga' },
  { id: 'm37',  name: 'M37 — Open Cluster',           cat: 'Messier', type: 'Open cluster · Auriga' },
  { id: 'm38',  name: 'M38 — Open Cluster',           cat: 'Messier', type: 'Open cluster · Auriga' },
  { id: 'm39',  name: 'M39 — Open Cluster',           cat: 'Messier', type: 'Open cluster · Cygnus' },
  { id: 'm40',  name: 'M40 — Double Star',            cat: 'Messier', type: 'Double star · Ursa Major' },
  { id: 'm41',  name: 'M41 — Open Cluster',           cat: 'Messier', type: 'Open cluster · Canis Major' },
  { id: 'm42',  name: 'M42 — Orion Nebula',           cat: 'Messier', type: 'Emission nebula · Orion' },
  { id: 'm43',  name: 'M43 — De Mairan\'s Nebula',    cat: 'Messier', type: 'Emission nebula · Orion' },
  { id: 'm44',  name: 'M44 — Beehive Cluster',        cat: 'Messier', type: 'Open cluster · Cancer' },
  { id: 'm45',  name: 'M45 — Pleiades',               cat: 'Messier', type: 'Open cluster · Taurus' },
  { id: 'm46',  name: 'M46 — Open Cluster',           cat: 'Messier', type: 'Open cluster · Puppis' },
  { id: 'm47',  name: 'M47 — Open Cluster',           cat: 'Messier', type: 'Open cluster · Puppis' },
  { id: 'm48',  name: 'M48 — Open Cluster',           cat: 'Messier', type: 'Open cluster · Hydra' },
  { id: 'm49',  name: 'M49 — Elliptical Galaxy',      cat: 'Messier', type: 'Galaxy · Virgo' },
  { id: 'm50',  name: 'M50 — Open Cluster',           cat: 'Messier', type: 'Open cluster · Monoceros' },
  { id: 'm51',  name: 'M51 — Whirlpool Galaxy',       cat: 'Messier', type: 'Galaxy · Canes Venatici' },
  { id: 'm52',  name: 'M52 — Open Cluster',           cat: 'Messier', type: 'Open cluster · Cassiopeia' },
  { id: 'm53',  name: 'M53 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Coma Berenices' },
  { id: 'm54',  name: 'M54 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Sagittarius' },
  { id: 'm55',  name: 'M55 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Sagittarius' },
  { id: 'm56',  name: 'M56 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Lyra' },
  { id: 'm57',  name: 'M57 — Ring Nebula',            cat: 'Messier', type: 'Planetary nebula · Lyra' },
  { id: 'm58',  name: 'M58 — Spiral Galaxy',          cat: 'Messier', type: 'Galaxy · Virgo' },
  { id: 'm59',  name: 'M59 — Elliptical Galaxy',      cat: 'Messier', type: 'Galaxy · Virgo' },
  { id: 'm60',  name: 'M60 — Elliptical Galaxy',      cat: 'Messier', type: 'Galaxy · Virgo' },
  { id: 'm61',  name: 'M61 — Spiral Galaxy',          cat: 'Messier', type: 'Galaxy · Virgo' },
  { id: 'm62',  name: 'M62 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Ophiuchus' },
  { id: 'm63',  name: 'M63 — Sunflower Galaxy',       cat: 'Messier', type: 'Galaxy · Canes Venatici' },
  { id: 'm64',  name: 'M64 — Black Eye Galaxy',       cat: 'Messier', type: 'Galaxy · Coma Berenices' },
  { id: 'm65',  name: 'M65 — Leo Triplet',            cat: 'Messier', type: 'Galaxy · Leo' },
  { id: 'm66',  name: 'M66 — Leo Triplet',            cat: 'Messier', type: 'Galaxy · Leo' },
  { id: 'm67',  name: 'M67 — Open Cluster',           cat: 'Messier', type: 'Open cluster · Cancer' },
  { id: 'm68',  name: 'M68 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Hydra' },
  { id: 'm69',  name: 'M69 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Sagittarius' },
  { id: 'm70',  name: 'M70 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Sagittarius' },
  { id: 'm71',  name: 'M71 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Sagitta' },
  { id: 'm72',  name: 'M72 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Aquarius' },
  { id: 'm73',  name: 'M73 — Asterism',               cat: 'Messier', type: 'Asterism · Aquarius' },
  { id: 'm74',  name: 'M74 — Phantom Galaxy',         cat: 'Messier', type: 'Galaxy · Pisces' },
  { id: 'm75',  name: 'M75 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Sagittarius' },
  { id: 'm76',  name: 'M76 — Little Dumbbell Nebula', cat: 'Messier', type: 'Planetary nebula · Perseus' },
  { id: 'm77',  name: 'M77 — Seyfert Galaxy',         cat: 'Messier', type: 'Galaxy · Cetus' },
  { id: 'm78',  name: 'M78 — Reflection Nebula',      cat: 'Messier', type: 'Reflection nebula · Orion' },
  { id: 'm79',  name: 'M79 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Lepus' },
  { id: 'm80',  name: 'M80 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Scorpius' },
  { id: 'm81',  name: 'M81 — Bode\'s Galaxy',         cat: 'Messier', type: 'Galaxy · Ursa Major' },
  { id: 'm82',  name: 'M82 — Cigar Galaxy',           cat: 'Messier', type: 'Galaxy · Ursa Major' },
  { id: 'm83',  name: 'M83 — Southern Pinwheel',      cat: 'Messier', type: 'Galaxy · Hydra' },
  { id: 'm84',  name: 'M84 — Elliptical Galaxy',      cat: 'Messier', type: 'Galaxy · Virgo' },
  { id: 'm85',  name: 'M85 — Elliptical Galaxy',      cat: 'Messier', type: 'Galaxy · Coma Berenices' },
  { id: 'm86',  name: 'M86 — Elliptical Galaxy',      cat: 'Messier', type: 'Galaxy · Virgo' },
  { id: 'm87',  name: 'M87 — Virgo A Galaxy',         cat: 'Messier', type: 'Galaxy · Virgo' },
  { id: 'm88',  name: 'M88 — Spiral Galaxy',          cat: 'Messier', type: 'Galaxy · Coma Berenices' },
  { id: 'm89',  name: 'M89 — Elliptical Galaxy',      cat: 'Messier', type: 'Galaxy · Virgo' },
  { id: 'm90',  name: 'M90 — Elliptical Galaxy',      cat: 'Messier', type: 'Galaxy · Virgo' },
  { id: 'm91',  name: 'M91 — Barred Spiral Galaxy',   cat: 'Messier', type: 'Galaxy · Coma Berenices' },
  { id: 'm92',  name: 'M92 — Globular Cluster',       cat: 'Messier', type: 'Globular cluster · Hercules' },
  { id: 'm93',  name: 'M93 — Open Cluster',           cat: 'Messier', type: 'Open cluster · Puppis' },
  { id: 'm94',  name: 'M94 — Croc\'s Eye Galaxy',     cat: 'Messier', type: 'Galaxy · Canes Venatici' },
  { id: 'm95',  name: 'M95 — Barred Spiral Galaxy',   cat: 'Messier', type: 'Galaxy · Leo' },
  { id: 'm96',  name: 'M96 — Spiral Galaxy',          cat: 'Messier', type: 'Galaxy · Leo' },
  { id: 'm97',  name: 'M97 — Owl Nebula',             cat: 'Messier', type: 'Planetary nebula · Ursa Major' },
  { id: 'm98',  name: 'M98 — Spiral Galaxy',          cat: 'Messier', type: 'Galaxy · Coma Berenices' },
  { id: 'm99',  name: 'M99 — Coma Pinwheel',          cat: 'Messier', type: 'Galaxy · Coma Berenices' },
  { id: 'm100', name: 'M100 — Grand Design Spiral',   cat: 'Messier', type: 'Galaxy · Coma Berenices' },
  { id: 'm101', name: 'M101 — Pinwheel Galaxy',       cat: 'Messier', type: 'Galaxy · Ursa Major' },
  { id: 'm102', name: 'M102 — Spindle Galaxy',        cat: 'Messier', type: 'Galaxy · Draco' },
  { id: 'm103', name: 'M103 — Open Cluster',          cat: 'Messier', type: 'Open cluster · Cassiopeia' },
  { id: 'm104', name: 'M104 — Sombrero Galaxy',       cat: 'Messier', type: 'Galaxy · Virgo' },
  { id: 'm105', name: 'M105 — Elliptical Galaxy',     cat: 'Messier', type: 'Galaxy · Leo' },
  { id: 'm106', name: 'M106 — Spiral Galaxy',         cat: 'Messier', type: 'Galaxy · Canes Venatici' },
  { id: 'm107', name: 'M107 — Globular Cluster',      cat: 'Messier', type: 'Globular cluster · Ophiuchus' },
  { id: 'm108', name: 'M108 — Surfboard Galaxy',      cat: 'Messier', type: 'Galaxy · Ursa Major' },
  { id: 'm109', name: 'M109 — Barred Spiral Galaxy',  cat: 'Messier', type: 'Galaxy · Ursa Major' },
  { id: 'm110', name: 'M110 — Andromeda Companion',   cat: 'Messier', type: 'Galaxy · Andromeda' },

  // ── NOTABLE NGCs ──────────────────────────────────────────────────────────
  { id: 'ngc104',  name: 'NGC 104 — 47 Tucanae',            cat: 'NGC', type: 'Globular cluster · Tucana' },
  { id: 'ngc253',  name: 'NGC 253 — Sculptor Galaxy',       cat: 'NGC', type: 'Galaxy · Sculptor' },
  { id: 'ngc869',  name: 'NGC 869 — Double Cluster (h Per)',cat: 'NGC', type: 'Open cluster · Perseus' },
  { id: 'ngc884',  name: 'NGC 884 — Double Cluster (χ Per)',cat: 'NGC', type: 'Open cluster · Perseus' },
  { id: 'ngc2244', name: 'NGC 2244 — Rosette Cluster',      cat: 'NGC', type: 'Open cluster · Monoceros' },
  { id: 'ngc2392', name: 'NGC 2392 — Eskimo Nebula',        cat: 'NGC', type: 'Planetary nebula · Gemini' },
  { id: 'ngc2438', name: 'NGC 2438 — Planetary in M46',     cat: 'NGC', type: 'Planetary nebula · Puppis' },
  { id: 'ngc3242', name: 'NGC 3242 — Ghost of Jupiter',     cat: 'NGC', type: 'Planetary nebula · Hydra' },
  { id: 'ngc3628', name: 'NGC 3628 — Hamburger Galaxy',     cat: 'NGC', type: 'Galaxy · Leo' },
  { id: 'ngc4565', name: 'NGC 4565 — Needle Galaxy',        cat: 'NGC', type: 'Galaxy · Coma Berenices' },
  { id: 'ngc4631', name: 'NGC 4631 — Whale Galaxy',         cat: 'NGC', type: 'Galaxy · Canes Venatici' },
  { id: 'ngc5128', name: 'NGC 5128 — Centaurus A',          cat: 'NGC', type: 'Galaxy · Centaurus' },
  { id: 'ngc5195', name: 'NGC 5195 — M51 Companion',        cat: 'NGC', type: 'Galaxy · Canes Venatici' },
  { id: 'ngc6231', name: 'NGC 6231 — Northern Jewel Box',   cat: 'NGC', type: 'Open cluster · Scorpius' },
  { id: 'ngc6992', name: 'NGC 6992 — Eastern Veil Nebula',  cat: 'NGC', type: 'Supernova remnant · Cygnus' },
  { id: 'ngc7000', name: 'NGC 7000 — North America Nebula', cat: 'NGC', type: 'Emission nebula · Cygnus' },
  { id: 'ngc7009', name: 'NGC 7009 — Saturn Nebula',        cat: 'NGC', type: 'Planetary nebula · Aquarius' },
  { id: 'ngc7293', name: 'NGC 7293 — Helix Nebula',         cat: 'NGC', type: 'Planetary nebula · Aquarius' },
  { id: 'ngc7331', name: 'NGC 7331 — Deer Lick Galaxy',     cat: 'NGC', type: 'Galaxy · Pegasus' },
  { id: 'ngc7789', name: 'NGC 7789 — Caroline\'s Rose',     cat: 'NGC', type: 'Open cluster · Cassiopeia' },

  // ── DOUBLE & MULTIPLE STARS ───────────────────────────────────────────────
  { id: 'albireo',   name: 'Albireo — β Cygni',           cat: 'Double Star', type: 'Gold+blue pair · Cygnus · sep 34″' },
  { id: 'algieba',   name: 'Algieba — γ Leonis',           cat: 'Double Star', type: 'Golden pair · Leo · sep 4.6″' },
  { id: 'mizar',     name: 'Mizar & Alcor — ζ UMa',        cat: 'Double Star', type: 'Naked-eye double · Ursa Major' },
  { id: 'castor',    name: 'Castor — α Geminorum',         cat: 'Double Star', type: 'White pair · Gemini · sep 5″' },
  { id: 'eps_lyr',   name: 'Epsilon Lyrae — Double Double', cat: 'Double Star', type: 'Quadruple system · Lyra · sep 3.5″/2.3″' },
  { id: 'eta_cas',   name: 'Eta Cassiopeiae — Achird',     cat: 'Double Star', type: 'Yellow+red pair · Cassiopeia · sep 13″' },
  { id: 'iota_cas',  name: 'Iota Cassiopeiae',              cat: 'Double Star', type: 'Triple system · Cassiopeia · sep 2.9″' },
  { id: 'theta_ori', name: 'Trapezium — θ¹ Orionis',       cat: 'Double Star', type: 'Quadruple · Orion · in M42 core' },
  { id: 'alpha_her', name: 'Rasalgethi — α Herculis',      cat: 'Double Star', type: 'Red giant pair · Hercules · sep 4.7″' },
  { id: 'zeta_lyr',  name: 'Zeta Lyrae',                   cat: 'Double Star', type: 'Wide pair · Lyra · sep 44″' },
  { id: 'nu_dra',    name: 'Nu Draconis — Kuma',           cat: 'Double Star', type: 'Easy white pair · Draco · sep 62″' },
  { id: 'beta_sco',  name: 'Graffias — β Scorpii',         cat: 'Double Star', type: 'Blue-white pair · Scorpius · sep 13″' },
  { id: '61_cyg',    name: '61 Cygni',                     cat: 'Double Star', type: 'Nearby orange pair · Cygnus · sep 29″' },

]; // end SKY_OBJECTS_DB
